# Generated by Django 3.2.9 on 2021-12-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=20)),
                ('address_line', models.TextField(verbose_name='Address')),
                ('postal_code', models.PositiveSmallIntegerField()),
                ('contact_no', models.PositiveIntegerField()),
            ],
        ),
    ]
